/* DoG RaceHub v1.89 · multilingual UI */
(function(){
  const LANGS={
    de:{label:'Deutsch',flag:'🇩🇪'},
    en:{label:'English',flag:'🇬🇧'},
    pl:{label:'Polski',flag:'🇵🇱'},
    es:{label:'Español',flag:'🇪🇸'},
    da:{label:'Dansk',flag:'🇩🇰'}
  };
  const D={
    en:{
      'Dashboard':'Dashboard','Fahrer':'Drivers','Vergleich':'Compare','Teams':'Teams','Rennen':'Races','Fahrer-WM':'Drivers’ Championship','KWM':'Constructors’ Championship','Archiv':'Archive','Saisonarchiv':'Season Archive',
      'AKTUELLE SAISON':'CURRENT SEASON','AKTIVE SAISON':'ACTIVE SEASON','ARCHIV':'ARCHIVE','Division 1 & 2':'Division 1 & 2','System bereit':'System ready','Bearbeiten':'Edit','App installieren':'Install app',
      'Deine Liga. Deine Daten.':'Your league. Your data.','Dein RaceHub.':'Your RaceHub.','Fahrer, Teams, Rennen und Meisterschaften – sauber getrennt, nachvollziehbar und jederzeit erweiterbar.':'Drivers, teams, races and championships – clearly separated, traceable and expandable at any time.',
      'Stammfahrer':'Full-time Driver','Ersatzfahrer':'Reserve Driver','Free Agent':'Free Agent','Nicht verfügbar':'Unavailable','Teams':'Teams','Divisionen':'Divisions','Erfasste Rennen':'Recorded races','aktuelle Saison':'current season','alle aktiven Teams':'all active teams',
      'Schnellzugriff':'Quick access','Die wichtigsten Bereiche':'The most important areas','Einzelakte & Marktwert':'Driver profile & market value','Fahrer & Fahrzeuge':'Drivers & cars','Ergebnisse & Screenshots':'Results & screenshots','Div 1 und Div 2':'Division 1 and Division 2',
      'Eine kompakte, vollständige Übersicht aller Fahrer.':'A compact, complete overview of all drivers.','Fahrer suchen ...':'Search drivers ...','Alle':'All','Fahrer hinzufügen':'Add driver','Fahrer auswählen':'Select driver',
      'Aktuelle Teamstruktur · Fahrzeug klein neben dem Teamnamen.':'Current team structure · small car next to team name.','Transfers':'Transfers','Division auswählen und die Fahrer-WM anzeigen.':'Select a division and view the Drivers’ Championship.','Konstrukteurs-WM mit Div 1, Div 2 oder Gesamt.':'Constructors’ Championship with Division 1, Division 2 or Overall.',
      'Division → Strecke → Ergebnis. Die Strecke wird anhand des gespeicherten Rennens eindeutig zugeordnet.':'Division → track → result. The track is uniquely assigned using the saved race.','Rennen hinzufügen':'Add race','Saison':'Season','Division':'Division','Strecke':'Track',
      'Historische Rennstände und Regelversionen der DoG-Saisons.':'Historical race standings and rule versions of DoG seasons.','Offiziell · 1. Saison':'Official · 1st season','aktiv':'active',
      'Nationalität':'Nationality','Fahrername':'Driver name','Aktueller Status':'Current status','Fahrernummer':'Driver number','Team':'Team','Abbrechen':'Cancel','Speichern':'Save','Schließen':'Close','Fertig':'Done','Prüfen':'Review','Ergebnis':'Result','Pos.':'Pos.','Zeit':'Time','Zeitstrafe (Sek.)':'Time penalty (sec.)','Nachträgliche Strafe':'Post-race penalty','Strafenbild':'Penalty image','Startposition':'Grid position','Startkapital':'Starting capital',
      'keine Nationalität':'no nationality','— keine Nationalität —':'— no nationality —','— keine Nummer —':'— no number —','Keine Nummer':'No number','— kein Team / Free Agent —':'— no team / free agent —','— Fahrer wählen —':'— select driver —','— leer —':'— empty —','— nicht gesetzt —':'— not set —','— Free Agent / keine Leihgebühr an Team —':'— Free Agent / no team loan fee —',
      'Rennhistorie':'Race history','Vertrag':'Contract','Finanzen':'Finances','Marktwert':'Market value','Performance':'Performance','Erfahrung':'Experience','Zuverlässigkeit':'Reliability','Rennleistung':'Race performance','Qualifying':'Qualifying','Fahrerprofil':'Driver profile','Gefahrene Fahrzeuge':'Driven cars','Erfolge':'Achievements','Wert-Snapshots':'Value snapshots',
      'Gesamt / OVA':'Overall / OVA','AKTUELLER STAND':'CURRENT STATUS','FAHRERAKTE · AKTUELLER STAND':'DRIVER FILE · CURRENT STATUS','FAHRER':'DRIVER','TEAMCHEF':'TEAM PRINCIPAL','TEAM CHEF':'TEAM PRINCIPAL','GEHALT':'SALARY','VERTRAG':'CONTRACT','SAISON/LAUFZEIT':'SEASON / TERM','LAUFZEIT':'TERM','AUSSTIEGSKLAUSEL':'RELEASE CLAUSE','ABFINDUNG':'SEVERANCE','SONDERZAHLUNG':'SPECIAL PAYMENT','FAHRERSPONSOR':'DRIVER SPONSOR',
      'Rennsieg':'Race win','Rennpace':'Race pace','Pole Position':'Pole position','Quali-König':'Qualifying king','Überholjäger':'Overtaking leader','Allrounder':'All-rounder','Elite Fahrer':'Elite driver','Routinierter Fahrer':'Experienced driver','Etablierter Fahrer':'Established driver','Nachwuchsfahrer':'Rising driver','Newcomer':'Newcomer','Veteran':'Veteran',
      '3 Rennsiege':'3 race wins','3 Podiumsplatzierungen':'3 podium finishes','7 Podiumsplatzierungen':'7 podium finishes','Fahrer Top 3 im Rennen':'Driver finishes Top 3','Fahrer Top 5 im Rennen':'Driver finishes Top 5','Fahrer Top 8 im Rennen':'Driver finishes Top 8','Fahrer Top 10 im Rennen':'Driver finishes Top 10','Fahrer Top 4 im Qualifying':'Driver qualifies Top 4','Fahrer Top 7 im Qualifying':'Driver qualifies Top 7','Fahrer nicht Letzter in Q2':'Driver not last in Q2','Durchschnittsplatzierung P7':'Average finish P7','Durchschnittsplatzierung P10':'Average finish P10','Durchschnittsplatzierung P15':'Average finish P15',
      'Lizenz':'License','Fahrer-Lizenz':'Driver license','Priorität nächste Saison':'Next season priority','Lizenzbedarf':'License cost','Lizenz am Saisonende buchen':'Book license at end of season','Aktuelle Saison':'Current season','nächste Saison':'next season','Budget':'Budget','verfügbar':'available','nicht genügend Budget':'insufficient budget','Nicht genügend Budget':'Insufficient budget',
      'Renn-Highlights':'Race highlights','Highlights bearbeiten':'Edit highlights','Highlights speichern':'Save highlights','Highlights geändert':'Highlights changed','Highlights gespeichert.':'Highlights saved.','Sieger':'Winner','Schnellste Runde':'Fastest lap','Fahrer des Tages':'Driver of the Day','Meiste Überholmanöver':'Most overtakes','Sauberster Fahrer':'Cleanest driver',
      'Rennen bearbeiten':'Edit race','Ergebnisdaten und normale Zeitstrafen können korrigiert werden.':'Result data and normal time penalties can be corrected.','Änderungen speichern':'Save changes','Rennen aktualisiert · WM/KWM/Fahrerwerte neu berechnet.':'Race updated · championship and driver ratings recalculated.',
      'OCR-Bibliothek konnte nicht geladen werden.':'OCR library could not be loaded.','OCR-Vorschläge übernommen. Bitte Vertrag prüfen, Unterschriften ergänzen und speichern.':'OCR suggestions applied. Please review the contract, add signatures and save.','OCR wird vorbereitet …':'Preparing OCR …','Ergebnistabelle wird zeilenweise gelesen …':'Reading result table row by row …','Vertrag wird mehrfach gelesen …':'Reading contract multiple times …','Highlight-Screenshot analysieren':'Analyze highlight screenshot','Renn-Screenshots':'Race screenshots','Screenshot hinzugefügt.':'Screenshot added.','Rennbild':'Race image',
      'Sponsor':'Sponsor','Sponsoren':'Sponsors','Sofortzahlung':'Upfront payment','Saisonziel':'Season goal','Rennziel':'Race goal','Gesamt ohne variable Zielanzahl':'Total without variable goal count','pro Rennziel':'per race goal','Finanzbuchung gespeichert.':'Financial transaction saved.','Fahrerfinanzen':'Driver finances','Fahrerfinanzen neu aus Verträgen, Leihen und Rennen berechnet.':'Driver finances recalculated from contracts, loans and races.','Noch keine Fahrer-Finanzbuchungen.':'No driver financial transactions yet.','Noch keine Buchungen vorhanden.':'No bookings yet.',
      'Transfer':'Transfer','Leihe':'Loan','Ersatzfahrer-Leihe':'Reserve driver loan','Leihgebühr':'Loan fee','ausleihendes Team':'borrowing team','Quellteam':'source team','Zielteam':'target team','Transfer/Ablöse':'Transfer/fee','Transfer vorgemerkt':'Transfer pending','vollzogen':'completed','vorgemerkt':'pending',
      'Noch keine Rennhistorie vorhanden.':'No race history yet.','Noch kein Vertrag gespeichert.':'No contract saved yet.','Keine Verträge für diese Saison.':'No contracts for this season.','Für diese Saison sind noch keine Verträge hinterlegt.':'No contracts have been saved for this season.','Für dieses Team sind in der aktuellen Saison noch keine Verträge hinterlegt.':'No contracts have been saved for this team in the current season.','Für diese Saison sind noch keine Transfers hinterlegt.':'No transfers have been saved for this season.','Keine Ersatzfahrer-Leihen in dieser Saison.':'No reserve-driver loans in this season.','Für diese Auswahl liegen noch keine Rennergebnisse vor.':'No race results are available for this selection yet.','Für diese Division liegen noch keine Rennergebnisse vor.':'No race results are available for this division yet.','Noch keine Rennen':'No races yet','Keine':'None',
      'Fahrer angelegt.':'Driver created.','Fahrer gespeichert.':'Driver saved.','Vertrag gespeichert':'Contract saved','Vertrag gelöscht und verknüpfte Fahrer-Finanzbuchungen entfernt.':'Contract deleted and linked driver financial transactions removed.','Datenbank neu berechnet':'Database recalculated','Datenbank neu berechnet · WM/KWM/Fahrerwerte aktualisiert.':'Database recalculated · championships and driver ratings updated.','Startguthaben gespeichert.':'Starting balance saved.','Budget-Cap gespeichert.':'Budget cap saved.','Code ist nicht korrekt.':'Code is incorrect.','Bearbeitung freigeschaltet.':'Editing unlocked.',
      'Rennen angelegt':'Race created','Rennen bearbeitet':'Race edited','Rennen nicht gefunden.':'Race not found.','Keine Strecke ausgewählt.':'No track selected.','Bitte eine Strecke eingeben.':'Please enter a track.','Bitte ein Zielteam auswählen.':'Please select a target team.','Zielteam nicht gefunden.':'Target team not found.','Ungültiges Saisonformat.':'Invalid season format.','Ein Fahrer darf im Team nicht doppelt eingetragen werden.':'A driver may not be entered twice in the same team.','Historische Fahrerwerte werden pro Rennstand gespeichert.':'Historical driver values are stored per race state.',
      'Fahrerpunktkosten':'Driver point cost','Punkteplatzierung':'Points position','Punkte':'Points','Gesamt':'Overall','aktuell':'current','Historie':'History','Regelversion':'rule version','Bekannter Fahrer':'Known driver','Ähnlicher Name':'Similar name','Neuer Fahrer':'New driver','Prüfung nötig':'Review required','Offen':'Open','Beendet':'Finished','Vorläufig':'Provisional','Vollzogen':'Completed','Aktiv':'Active','Wieder aktivieren':'Reactivate',
      'Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.':'Reserve driver, borrowing team and loan fee are required.','Stammfahrer haben immer Vorrang vor Ersatzfahrern bei der Vergabe.':'Full-time drivers always have priority over reserve drivers when assigning numbers.','Aktuelle F1 / gesperrt':'Current F1 / blocked','F1 gesperrt':'F1 blocked','frei':'free','genommen':'taken','Fahrerfinanzen neu aus Verträgen, Leihen und Rennen berechnet.':'Driver finances recalculated from contracts, loans and races.',
      'KONSTRUKTEURS-MEISTER':'CONSTRUCTORS’ CHAMPION','Offiziell · 1. Saison':'Official · 1st season','Start 02/26':'Start 02/26','Rennen':'Races','Rennschema':'Race format','aus Renndaten':'from race data','manuell':'manual','Datum offen':'Date open','keine Strafe':'no penalty','keine Zeitstrafe':'no time penalty','nicht dnf/dsq':'not DNF/DSQ','nicht letzter in q2':'not last in Q2',
      'Deutschland':'Germany','Schweiz':'Switzerland','Spanien':'Spain','Österreich':'Austria','Großbritannien':'United Kingdom','Dänemark':'Denmark','Schweden':'Sweden','Portugal':'Portugal','Norwegen':'Norway','Polen':'Poland',
      'App installieren':'Install app','System bereit':'System ready','CURRENT':'CURRENT'
    },
    pl:{
      'Dashboard':'Panel','Fahrer':'Kierowcy','Vergleich':'Porównanie','Teams':'Zespoły','Rennen':'Wyścigi','Fahrer-WM':'Mistrzostwa kierowców','KWM':'Mistrzostwa konstruktorów','Archiv':'Archiwum','Saisonarchiv':'Archiwum sezonu','AKTUELLE SAISON':'AKTUALNY SEZON','AKTIVE SAISON':'AKTYWNY SEZON','ARCHIV':'ARCHIWUM','Bearbeiten':'Edytuj','App installieren':'Zainstaluj aplikację','System bereit':'System gotowy',
      'Stammfahrer':'Kierowca etatowy','Ersatzfahrer':'Kierowca rezerwowy','Free Agent':'Wolny agent','Nicht verfügbar':'Niedostępny','Teams':'Zespoły','Divisionen':'Dywizje','Erfasste Rennen':'Zarejestrowane wyścigi','aktuelle Saison':'aktualny sezon','alle aktiven Teams':'wszystkie aktywne zespoły','Schnellzugriff':'Szybki dostęp','Die wichtigsten Bereiche':'Najważniejsze obszary','Fahrer hinzufügen':'Dodaj kierowcę','Fahrer auswählen':'Wybierz kierowcę','Fahrer suchen ...':'Szukaj kierowcy ...','Alle':'Wszystkie',
      'Transfers':'Transfery','Rennen hinzufügen':'Dodaj wyścig','Saison':'Sezon','Division':'Dywizja','Strecke':'Tor','Nationalität':'Narodowość','Fahrername':'Imię i nazwisko kierowcy','Aktueller Status':'Aktualny status','Fahrernummer':'Numer kierowcy','Team':'Zespół','Abbrechen':'Anuluj','Speichern':'Zapisz','Fertig':'Gotowe','Prüfen':'Sprawdź','Ergebnis':'Wynik','Zeit':'Czas','Zeitstrafe (Sek.)':'Kara czasowa (sek.)','Startposition':'Pozycja startowa','Startkapital':'Kapitał początkowy',
      'Rennhistorie':'Historia wyścigów','Vertrag':'Kontrakt','Finanzen':'Finanse','Marktwert':'Wartość rynkowa','Performance':'Wydajność','Erfahrung':'Doświadczenie','Zuverlässigkeit':'Niezawodność','Rennleistung':'Wyniki wyścigowe','Qualifying':'Kwalifikacje','Fahrerprofil':'Profil kierowcy','Gefahrene Fahrzeuge':'Prowadzone samochody','Erfolge':'Osiągnięcia','Wert-Snapshots':'Historia wartości','Gesamt / OVA':'Ogólna / OVA','Fahrer-Lizenz':'Licencja kierowcy','Lizenz':'Licencja','Priorität nächste Saison':'Priorytet na następny sezon','Lizenzbedarf':'Koszt licencji','Aktuelle Saison':'Aktualny sezon','nächste Saison':'następny sezon','Budget':'Budżet','verfügbar':'dostępne','Nicht genügend Budget':'Niewystarczający budżet',
      'Renn-Highlights':'Najważniejsze momenty wyścigu','Highlights bearbeiten':'Edytuj najważniejsze momenty','Highlights speichern':'Zapisz najważniejsze momenty','Sieger':'Zwycięzca','Schnellste Runde':'Najszybsze okrążenie','Fahrer des Tages':'Kierowca dnia','Meiste Überholmanöver':'Najwięcej wyprzedzeń','Sauberster Fahrer':'Najczystszy kierowca','Rennen bearbeiten':'Edytuj wyścig','Änderungen speichern':'Zapisz zmiany','Sponsor':'Sponsor','Sofortzahlung':'Płatność z góry','Saisonziel':'Cel sezonu','Rennziel':'Cel wyścigu','Gesamt':'Łącznie','Punkte':'Punkty','Punkteplatzierung':'Pozycja punktowana','Transfer':'Transfer','Leihe':'Wypożyczenie','Leihgebühr':'Opłata za wypożyczenie',
      'Noch keine Rennhistorie vorhanden.':'Brak historii wyścigów.','Noch kein Vertrag gespeichert.':'Brak zapisanego kontraktu.','Keine Verträge für diese Saison.':'Brak kontraktów w tym sezonie.','Noch keine Buchungen vorhanden.':'Brak księgowań.','Keine':'Brak','Fahrer angelegt.':'Kierowca utworzony.','Fahrer gespeichert.':'Kierowca zapisany.','Vertrag gespeichert':'Kontrakt zapisany','Datenbank neu berechnet':'Baza danych przeliczona','Startguthaben gespeichert.':'Kapitał początkowy zapisany.','Budget-Cap gespeichert.':'Limit budżetowy zapisany.','Code ist nicht korrekt.':'Kod jest nieprawidłowy.','Bearbeitung freigeschaltet.':'Edycja odblokowana.','Rennen angelegt':'Wyścig utworzony','Rennen bearbeitet':'Wyścig edytowany','Rennen nicht gefunden.':'Nie znaleziono wyścigu.','Keine Strecke ausgewählt.':'Nie wybrano toru.','Bitte eine Strecke eingeben.':'Wprowadź tor.','Bitte ein Zielteam auswählen.':'Wybierz zespół docelowy.','Ungültiges Saisonformat.':'Nieprawidłowy format sezonu.','Bekannter Fahrer':'Znany kierowca','Ähnlicher Name':'Podobna nazwa','Neuer Fahrer':'Nowy kierowca','Prüfung nötig':'Wymagana kontrola','Offen':'Otwarte','Beendet':'Zakończone','Vorläufig':'Wstępne','Vollzogen':'Zrealizowane','Aktiv':'Aktywne','Wieder aktivieren':'Aktywuj ponownie','frei':'wolny','genommen':'zajęty',
      'Deutschland':'Niemcy','Schweiz':'Szwajcaria','Spanien':'Hiszpania','Österreich':'Austria','Großbritannien':'Wielka Brytania','Dänemark':'Dania','Schweden':'Szwecja','Portugal':'Portugalia','Norwegen':'Norwegia','Polen':'Polska'
    },
    es:{
      'Dashboard':'Panel','Fahrer':'Pilotos','Vergleich':'Comparación','Teams':'Equipos','Rennen':'Carreras','Fahrer-WM':'Campeonato de Pilotos','KWM':'Campeonato de Constructores','Archiv':'Archivo','Saisonarchiv':'Archivo de temporada','AKTUELLE SAISON':'TEMPORADA ACTUAL','AKTIVE SAISON':'TEMPORADA ACTIVA','ARCHIV':'ARCHIVO','Bearbeiten':'Editar','App installieren':'Instalar app','System bereit':'Sistema listo',
      'Stammfahrer':'Piloto titular','Ersatzfahrer':'Piloto reserva','Free Agent':'Agente libre','Nicht verfügbar':'No disponible','Divisionen':'Divisiones','Erfasste Rennen':'Carreras registradas','aktuelle Saison':'temporada actual','alle aktiven Teams':'todos los equipos activos','Schnellzugriff':'Acceso rápido','Die wichtigsten Bereiche':'Áreas principales','Fahrer hinzufügen':'Añadir piloto','Fahrer auswählen':'Seleccionar piloto','Fahrer suchen ...':'Buscar pilotos ...','Alle':'Todos',
      'Transfers':'Transferencias','Rennen hinzufügen':'Añadir carrera','Saison':'Temporada','Division':'División','Strecke':'Circuito','Nationalität':'Nacionalidad','Fahrername':'Nombre del piloto','Aktueller Status':'Estado actual','Fahrernummer':'Número del piloto','Team':'Equipo','Abbrechen':'Cancelar','Speichern':'Guardar','Fertig':'Listo','Prüfen':'Revisar','Ergebnis':'Resultado','Zeit':'Tiempo','Zeitstrafe (Sek.)':'Penalización de tiempo (seg.)','Startposition':'Posición de salida','Startkapital':'Capital inicial',
      'Rennhistorie':'Historial de carreras','Vertrag':'Contrato','Finanzen':'Finanzas','Marktwert':'Valor de mercado','Performance':'Rendimiento','Erfahrung':'Experiencia','Zuverlässigkeit':'Fiabilidad','Rennleistung':'Rendimiento en carrera','Qualifying':'Clasificación','Fahrerprofil':'Perfil del piloto','Gefahrene Fahrzeuge':'Coches conducidos','Erfolge':'Logros','Wert-Snapshots':'Historial de valor','Gesamt / OVA':'General / OVA','Fahrer-Lizenz':'Licencia del piloto','Lizenz':'Licencia','Priorität nächste Saison':'Prioridad próxima temporada','Lizenzbedarf':'Coste de licencia','Aktuelle Saison':'Temporada actual','nächste Saison':'próxima temporada','Budget':'Presupuesto','verfügbar':'disponible','Nicht genügend Budget':'Presupuesto insuficiente',
      'Renn-Highlights':'Momentos destacados','Highlights bearbeiten':'Editar destacados','Highlights speichern':'Guardar destacados','Sieger':'Ganador','Schnellste Runde':'Vuelta rápida','Fahrer des Tages':'Piloto del día','Meiste Überholmanöver':'Más adelantamientos','Sauberster Fahrer':'Piloto más limpio','Rennen bearbeiten':'Editar carrera','Änderungen speichern':'Guardar cambios','Sponsor':'Patrocinador','Sofortzahlung':'Pago inicial','Saisonziel':'Objetivo de temporada','Rennziel':'Objetivo de carrera','Gesamt':'Total','Punkte':'Puntos','Punkteplatzierung':'Posición de puntos','Transfer':'Transferencia','Leihe':'Préstamo','Leihgebühr':'Tarifa de préstamo',
      'Noch keine Rennhistorie vorhanden.':'Aún no hay historial de carreras.','Noch kein Vertrag gespeichert.':'Aún no hay contrato guardado.','Keine Verträge für diese Saison.':'No hay contratos para esta temporada.','Noch keine Buchungen vorhanden.':'Aún no hay registros.','Keine':'Ninguno','Fahrer angelegt.':'Piloto creado.','Fahrer gespeichert.':'Piloto guardado.','Vertrag gespeichert':'Contrato guardado','Datenbank neu berechnet':'Base de datos recalculada','Startguthaben gespeichert.':'Saldo inicial guardado.','Budget-Cap gespeichert.':'Límite presupuestario guardado.','Code ist nicht korrekt.':'El código no es correcto.','Bearbeitung freigeschaltet.':'Edición desbloqueada.','Rennen angelegt':'Carrera creada','Rennen bearbeitet':'Carrera editada','Rennen nicht gefunden.':'Carrera no encontrada.','Keine Strecke ausgewählt.':'No se ha seleccionado circuito.','Bitte eine Strecke eingeben.':'Introduce un circuito.','Bitte ein Zielteam auswählen.':'Selecciona un equipo de destino.','Ungültiges Saisonformat.':'Formato de temporada no válido.','Bekannter Fahrer':'Piloto conocido','Ähnlicher Name':'Nombre similar','Neuer Fahrer':'Nuevo piloto','Prüfung nötig':'Revisión necesaria','Offen':'Abierto','Beendet':'Finalizado','Vorläufig':'Provisional','Vollzogen':'Completado','Aktiv':'Activo','Wieder aktivieren':'Reactivar','frei':'libre','genommen':'ocupado',
      'Deutschland':'Alemania','Schweiz':'Suiza','Spanien':'España','Österreich':'Austria','Großbritannien':'Reino Unido','Dänemark':'Dinamarca','Schweden':'Suecia','Portugal':'Portugal','Norwegen':'Noruega','Polen':'Polonia'
    },
    da:{
      'Dashboard':'Dashboard','Fahrer':'Kørere','Vergleich':'Sammenligning','Teams':'Teams','Rennen':'Løb','Fahrer-WM':'Kørermesterskab','KWM':'Konstruktørmesterskab','Archiv':'Arkiv','Saisonarchiv':'Sæsonarkiv','AKTUELLE SAISON':'AKTUEL SÆSON','AKTIVE SAISON':'AKTIV SÆSON','ARCHIV':'ARKIV','Bearbeiten':'Rediger','App installieren':'Installer app','System bereit':'System klar',
      'Stammfahrer':'Fast kører','Ersatzfahrer':'Reservekører','Free Agent':'Free Agent','Nicht verfügbar':'Ikke tilgængelig','Divisionen':'Divisioner','Erfasste Rennen':'Registrerede løb','aktuelle Saison':'aktuel sæson','alle aktiven Teams':'alle aktive teams','Schnellzugriff':'Hurtig adgang','Die wichtigsten Bereiche':'Vigtigste områder','Fahrer hinzufügen':'Tilføj kører','Fahrer auswählen':'Vælg kører','Fahrer suchen ...':'Søg efter kører ...','Alle':'Alle',
      'Transfers':'Transfers','Rennen hinzufügen':'Tilføj løb','Saison':'Sæson','Division':'Division','Strecke':'Bane','Nationalität':'Nationalitet','Fahrername':'Kørernavn','Aktueller Status':'Aktuel status','Fahrernummer':'Kørernummer','Team':'Team','Abbrechen':'Annuller','Speichern':'Gem','Fertig':'Færdig','Prüfen':'Kontroller','Ergebnis':'Resultat','Zeit':'Tid','Zeitstrafe (Sek.)':'Tidsstraf (sek.)','Startposition':'Startposition','Startkapital':'Startkapital',
      'Rennhistorie':'Løbshistorik','Vertrag':'Kontrakt','Finanzen':'Økonomi','Marktwert':'Markedsværdi','Performance':'Performance','Erfahrung':'Erfaring','Zuverlässigkeit':'Pålidelighed','Rennleistung':'Race performance','Qualifying':'Kvalifikation','Fahrerprofil':'Kørerprofil','Gefahrene Fahrzeuge':'Kørte biler','Erfolge':'Resultater','Wert-Snapshots':'Værdiudvikling','Gesamt / OVA':'Samlet / OVA','Fahrer-Lizenz':'Kørekort','Lizenz':'Licens','Priorität nächste Saison':'Prioritet næste sæson','Lizenzbedarf':'Licenspris','Aktuelle Saison':'Aktuel sæson','nächste Saison':'næste sæson','Budget':'Budget','verfügbar':'tilgængelig','Nicht genügend Budget':'Utilstrækkeligt budget',
      'Renn-Highlights':'Løbshøjdepunkter','Highlights bearbeiten':'Rediger højdepunkter','Highlights speichern':'Gem højdepunkter','Sieger':'Vinder','Schnellste Runde':'Hurtigste omgang','Fahrer des Tages':'Dagens kører','Meiste Überholmanöver':'Flest overhalinger','Sauberster Fahrer':'Reneste kører','Rennen bearbeiten':'Rediger løb','Änderungen speichern':'Gem ændringer','Sponsor':'Sponsor','Sofortzahlung':'Forudbetaling','Saisonziel':'Sæsonmål','Rennziel':'Løbsmål','Gesamt':'I alt','Punkte':'Point','Punkteplatzierung':'Pointplacering','Transfer':'Transfer','Leihe':'Lån','Leihgebühr':'Lånegebyr',
      'Noch keine Rennhistorie vorhanden.':'Ingen løbshistorik endnu.','Noch kein Vertrag gespeichert.':'Ingen kontrakt gemt endnu.','Keine Verträge für diese Saison.':'Ingen kontrakter for denne sæson.','Noch keine Buchungen vorhanden.':'Ingen posteringer endnu.','Keine':'Ingen','Fahrer angelegt.':'Kører oprettet.','Fahrer gespeichert.':'Kører gemt.','Vertrag gespeichert':'Kontrakt gemt','Datenbank neu berechnet':'Database genberegnet','Startguthaben gespeichert.':'Startsaldo gemt.','Budget-Cap gespeichert.':'Budgetloft gemt.','Code ist nicht korrekt.':'Koden er ikke korrekt.','Bearbeitung freigeschaltet.':'Redigering låst op.','Rennen angelegt':'Løb oprettet','Rennen bearbeitet':'Løb redigeret','Rennen nicht gefunden.':'Løb ikke fundet.','Keine Strecke ausgewählt.':'Ingen bane valgt.','Bitte eine Strecke eingeben.':'Indtast en bane.','Bitte ein Zielteam auswählen.':'Vælg et målteam.','Ungültiges Saisonformat.':'Ugyldigt sæsonformat.','Bekannter Fahrer':'Kendt kører','Ähnlicher Name':'Lignende navn','Neuer Fahrer':'Ny kører','Prüfung nötig':'Kontrol nødvendig','Offen':'Åben','Beendet':'Afsluttet','Vorläufig':'Foreløbig','Vollzogen':'Gennemført','Aktiv':'Aktiv','Wieder aktivieren':'Aktivér igen','frei':'ledig','genommen':'optaget',
      'Deutschland':'Tyskland','Schweiz':'Schweiz','Spanien':'Spanien','Österreich':'Østrig','Großbritannien':'Storbritannien','Dänemark':'Danmark','Schweden':'Sverige','Portugal':'Portugal','Norwegen':'Norge','Polen':'Polen'
    }
  };
  const EXTRA={
    en:{'FAHRER':'DRIVER','TEAMCHEF':'TEAM PRINCIPAL','TEAM CHEF':'TEAM PRINCIPAL','GEHALT':'SALARY','VERTRAG':'CONTRACT','SAISON/LAUFZEIT':'SEASON / TERM','LAUFZEIT':'TERM','AUSSTIEGSKLAUSEL':'RELEASE CLAUSE','ABFINDUNG':'SEVERANCE','SONDERZAHLUNG':'SPECIAL PAYMENT','FAHRERSPONSOR':'DRIVER SPONSOR','KONSTRUKTEURS-MEISTER':'CONSTRUCTORS’ CHAMPION','Rennsieg':'Race win','Rennpace':'Race pace','Pole Position':'Pole position','Quali-König':'Qualifying king','Überholjäger':'Overtaking leader','Allrounder':'All-rounder','Elite Fahrer':'Elite driver','Routinierter Fahrer':'Experienced driver','Etablierter Fahrer':'Established driver','Nachwuchsfahrer':'Rising driver','Newcomer':'Newcomer','Veteran':'Veteran','3 Rennsiege':'3 race wins','3 Podiumsplatzierungen':'3 podium finishes','7 Podiumsplatzierungen':'7 podium finishes','Fahrer Top 3 im Rennen':'Driver finishes Top 3','Fahrer Top 5 im Rennen':'Driver finishes Top 5','Fahrer Top 8 im Rennen':'Driver finishes Top 8','Fahrer Top 10 im Rennen':'Driver finishes Top 10','Fahrer Top 4 im Qualifying':'Driver qualifies Top 4','Fahrer Top 7 im Qualifying':'Driver qualifies Top 7','Fahrer nicht Letzter in Q2':'Driver not last in Q2','Durchschnittsplatzierung P7':'Average finish P7','Durchschnittsplatzierung P10':'Average finish P10','Durchschnittsplatzierung P15':'Average finish P15','Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.':'Reserve driver, borrowing team and loan fee are required.','Aktuelle F1 / gesperrt':'Current F1 / blocked','F1 gesperrt':'F1 blocked'},
    pl:{'FAHRER':'KIEROWCA','TEAMCHEF':'SZEF ZESPOŁU','TEAM CHEF':'SZEF ZESPOŁU','GEHALT':'PENSJA','VERTRAG':'KONTRAKT','SAISON/LAUFZEIT':'SEZON / OKRES','LAUFZEIT':'OKRES','AUSSTIEGSKLAUSEL':'KLAUZULA ODEJŚCIA','ABFINDUNG':'ODPRAWA','SONDERZAHLUNG':'PŁATNOŚĆ SPECJALNA','FAHRERSPONSOR':'SPONSOR KIEROWCY','KONSTRUKTEURS-MEISTER':'MISTRZ KONSTRUKTORÓW','Rennsieg':'Zwycięstwo','Rennpace':'Tempo wyścigowe','Pole Position':'Pole position','Quali-König':'Król kwalifikacji','Überholjäger':'Król wyprzedzania','Allrounder':'Wszechstronny','Elite Fahrer':'Elitarny kierowca','Routinierter Fahrer':'Doświadczony kierowca','Etablierter Fahrer':'Uznany kierowca','Nachwuchsfahrer':'Młody kierowca','Newcomer':'Debiutant','Veteran':'Weteran','3 Rennsiege':'3 zwycięstwa','3 Podiumsplatzierungen':'3 podia','7 Podiumsplatzierungen':'7 podiów','Fahrer Top 3 im Rennen':'Kierowca w Top 3','Fahrer Top 5 im Rennen':'Kierowca w Top 5','Fahrer Top 8 im Rennen':'Kierowca w Top 8','Fahrer Top 10 im Rennen':'Kierowca w Top 10','Fahrer Top 4 im Qualifying':'Kierowca w Top 4 kwalifikacji','Fahrer Top 7 im Qualifying':'Kierowca w Top 7 kwalifikacji','Fahrer nicht Letzter in Q2':'Kierowca nie jest ostatni w Q2','Durchschnittsplatzierung P7':'Średnia pozycja P7','Durchschnittsplatzierung P10':'Średnia pozycja P10','Durchschnittsplatzierung P15':'Średnia pozycja P15','Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.':'Wymagany kierowca rezerwowy, zespół wypożyczający i opłata.','Aktuelle F1 / gesperrt':'Aktualna F1 / zablokowane','F1 gesperrt':'Zablokowane w F1'},
    es:{'FAHRER':'PILOTO','TEAMCHEF':'JEFE DE EQUIPO','TEAM CHEF':'JEFE DE EQUIPO','GEHALT':'SALARIO','VERTRAG':'CONTRATO','SAISON/LAUFZEIT':'TEMPORADA / DURACIÓN','LAUFZEIT':'DURACIÓN','AUSSTIEGSKLAUSEL':'CLÁUSULA DE SALIDA','ABFINDUNG':'INDEMNIZACIÓN','SONDERZAHLUNG':'PAGO ESPECIAL','FAHRERSPONSOR':'PATROCINADOR DEL PILOTO','KONSTRUKTEURS-MEISTER':'CAMPEÓN DE CONSTRUCTORES','Rennsieg':'Victoria','Rennpace':'Ritmo de carrera','Pole Position':'Pole position','Quali-König':'Rey de la clasificación','Überholjäger':'Rey de los adelantamientos','Allrounder':'Polivalente','Elite Fahrer':'Piloto élite','Routinierter Fahrer':'Piloto experimentado','Etablierter Fahrer':'Piloto consolidado','Nachwuchsfahrer':'Piloto joven','Newcomer':'Novato','Veteran':'Veterano','3 Rennsiege':'3 victorias','3 Podiumsplatzierungen':'3 podios','7 Podiumsplatzierungen':'7 podios','Fahrer Top 3 im Rennen':'Piloto en Top 3','Fahrer Top 5 im Rennen':'Piloto en Top 5','Fahrer Top 8 im Rennen':'Piloto en Top 8','Fahrer Top 10 im Rennen':'Piloto en Top 10','Fahrer Top 4 im Qualifying':'Piloto en Top 4 de clasificación','Fahrer Top 7 im Qualifying':'Piloto en Top 7 de clasificación','Fahrer nicht Letzter in Q2':'Piloto no último en Q2','Durchschnittsplatzierung P7':'Promedio P7','Durchschnittsplatzierung P10':'Promedio P10','Durchschnittsplatzierung P15':'Promedio P15','Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.':'Se requieren piloto reserva, equipo prestatario y tarifa.','Aktuelle F1 / gesperrt':'F1 actual / bloqueado','F1 gesperrt':'Bloqueado en F1'},
    da:{'FAHRER':'KØRER','TEAMCHEF':'TEAMCHEF','TEAM CHEF':'TEAMCHEF','GEHALT':'LØN','VERTRAG':'KONTRAKT','SAISON/LAUFZEIT':'SÆSON / PERIODE','LAUFZEIT':'PERIODE','AUSSTIEGSKLAUSEL':'FRIGIVELSESKLAUSUL','ABFINDUNG':'FRATRÆDELSESGODTGØRELSE','SONDERZAHLUNG':'SÆRLIG BETALING','FAHRERSPONSOR':'KØRERSPONSOR','KONSTRUKTEURS-MEISTER':'KONSTRUKTØRMESTER','Rennsieg':'Løbssejr','Rennpace':'Race pace','Pole Position':'Pole position','Quali-König':'Kvalifikationskonge','Überholjäger':'Overhalingskonge','Allrounder':'Allrounder','Elite Fahrer':'Elitekører','Routinierter Fahrer':'Erfaren kører','Etablierter Fahrer':'Etableret kører','Nachwuchsfahrer':'Ung kører','Newcomer':'Ny kører','Veteran':'Veteran','3 Rennsiege':'3 løbssejre','3 Podiumsplatzierungen':'3 podieplaceringer','7 Podiumsplatzierungen':'7 podieplaceringer','Fahrer Top 3 im Rennen':'Kører i Top 3','Fahrer Top 5 im Rennen':'Kører i Top 5','Fahrer Top 8 im Rennen':'Kører i Top 8','Fahrer Top 10 im Rennen':'Kører i Top 10','Fahrer Top 4 im Qualifying':'Kører i Top 4 i kvalifikation','Fahrer Top 7 im Qualifying':'Kører i Top 7 i kvalifikation','Fahrer nicht Letzter in Q2':'Kører ikke sidst i Q2','Durchschnittsplatzierung P7':'Gennemsnit P7','Durchschnittsplatzierung P10':'Gennemsnit P10','Durchschnittsplatzierung P15':'Gennemsnit P15','Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.':'Reservekører, låneteam og lånegebyr kræves.','Aktuelle F1 / gesperrt':'Aktuel F1 / blokeret','F1 gesperrt':'Blokeret i F1'}
  };
  Object.keys(EXTRA).forEach(l=>{D[l]={...D[l],...EXTRA[l]};});
  // English-style keys reused where useful in all languages.
  const base={
    'FAHRER':'Fahrer','TEAMCHEF':'Teamchef','TEAM CHEF':'Teamchef','GEHALT':'Gehalt','VERTRAG':'Vertrag','SAISON/LAUFZEIT':'Saison / Laufzeit','LAUFZEIT':'Laufzeit','AUSSTIEGSKLAUSEL':'Ausstiegsklausel','ABFINDUNG':'Abfindung','SONDERZAHLUNG':'Sonderzahlung','FAHRERSPONSOR':'Fahrersponsor','KONSTRUKTEURS-MEISTER':'Konstrukteurs-Meister','Offiziell · 1. Saison':'Offiziell · 1. Saison','Start 02/26':'Start 02/26','Rennschema':'Rennschema','aus Renndaten':'aus Renndaten','manuell':'manuell','Datum offen':'Datum offen','keine Strafe':'keine Strafe','keine Zeitstrafe':'keine Zeitstrafe','nicht dnf/dsq':'nicht DNF/DSQ','nicht letzter in q2':'nicht letzter in Q2','Rennsieg':'Rennsieg','Rennpace':'Rennpace','Pole Position':'Pole Position','Quali-König':'Quali-König','Überholjäger':'Überholjäger','Allrounder':'Allrounder','Elite Fahrer':'Elite Fahrer','Routinierter Fahrer':'Routinierter Fahrer','Etablierter Fahrer':'Etablierter Fahrer','Nachwuchsfahrer':'Nachwuchsfahrer','Newcomer':'Newcomer','Veteran':'Veteran','3 Rennsiege':'3 Rennsiege','3 Podiumsplatzierungen':'3 Podiumsplatzierungen','7 Podiumsplatzierungen':'7 Podiumsplatzierungen','Fahrer Top 3 im Rennen':'Fahrer Top 3 im Rennen','Fahrer Top 5 im Rennen':'Fahrer Top 5 im Rennen','Fahrer Top 8 im Rennen':'Fahrer Top 8 im Rennen','Fahrer Top 10 im Rennen':'Fahrer Top 10 im Rennen','Fahrer Top 4 im Qualifying':'Fahrer Top 4 im Qualifying','Fahrer Top 7 im Qualifying':'Fahrer Top 7 im Qualifying','Fahrer nicht Letzter in Q2':'Fahrer nicht Letzter in Q2','Durchschnittsplatzierung P7':'Durchschnittsplatzierung P7','Durchschnittsplatzierung P10':'Durchschnittsplatzierung P10','Durchschnittsplatzierung P15':'Durchschnittsplatzierung P15','Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.':'Ersatzfahrer, ausleihendes Team und Leihgebühr erforderlich.','Aktuelle F1 / gesperrt':'Aktuelle F1 / gesperrt','F1 gesperrt':'F1 gesperrt','frei':'frei','genommen':'genommen'
  };
  Object.keys(D).forEach(l=>{if(l!=='de'){D[l]={...D[l]};}});
  D.de={...base,...D.de};
  const wordMaps={
    en:{'Fahrer':'Drivers','Team':'Team','Rennen':'Races','Saison':'Season','Division':'Division','Strecke':'Track','Vertrag':'Contract','Finanzen':'Finances','Punkte':'Points','Gesamt':'Overall','aktuell':'current','gespeichert':'saved','bearbeitet':'edited','angelegt':'created','Keine':'No','Noch':'No','Bitte':'Please','auswählen':'select','eingeben':'enter','Änderungen':'changes','speichern':'save','Sponsoren':'Sponsors','Lizenz':'License','Leihgebühr':'loan fee','Transfer':'transfer','Status':'status'},
    pl:{'Fahrer':'kierowca','Team':'zespół','Rennen':'wyścig','Saison':'sezon','Division':'dywizja','Strecke':'tor','Vertrag':'kontrakt','Finanzen':'finanse','Punkte':'punkty','Gesamt':'łącznie','aktuell':'aktualny','gespeichert':'zapisany','bearbeitet':'edytowany','angelegt':'utworzony','Keine':'Brak','Bitte':'Proszę','auswählen':'wybierz','eingeben':'wprowadź','Änderungen':'zmiany','speichern':'zapisz','Lizenz':'licencja','Transfer':'transfer','Status':'status'},
    es:{'Fahrer':'piloto','Team':'equipo','Rennen':'carreras','Saison':'temporada','Division':'división','Strecke':'circuito','Vertrag':'contrato','Finanzen':'finanzas','Punkte':'puntos','Gesamt':'total','aktuell':'actual','gespeichert':'guardado','bearbeitet':'editado','angelegt':'creado','Keine':'Ninguno','Bitte':'Por favor','auswählen':'seleccionar','eingeben':'introducir','Änderungen':'cambios','speichern':'guardar','Lizenz':'licencia','Transfer':'transferencia','Status':'estado'},
    da:{'Fahrer':'kører','Team':'team','Rennen':'løb','Saison':'sæson','Division':'division','Strecke':'bane','Vertrag':'kontrakt','Finanzen':'økonomi','Punkte':'point','Gesamt':'i alt','aktuell':'aktuel','gespeichert':'gemt','bearbeitet':'redigeret','angelegt':'oprettet','Keine':'Ingen','Bitte':'Venligst','auswählen':'vælg','eingeben':'indtast','Änderungen':'ændringer','speichern':'gem','Lizenz':'licens','Transfer':'transfer','Status':'status'}
  };
  let current=localStorage.getItem('dogrh_lang')||'de';
  function escapeRe(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
  function translateText(text,lang){
    if(!text||lang==='de')return text;
    const dict=D[lang]||D.en;
    const exact=dict[text.trim()];
    if(exact)return text.replace(text.trim(),exact);
    let out=text;
    const keys=Object.keys(dict).filter(k=>k.length>3).sort((a,b)=>b.length-a.length);
    for(const k of keys){
      if(out.includes(k))out=out.split(k).join(dict[k]);
      else if(k.length>3 && new RegExp('\\b'+escapeRe(k)+'\\b','i').test(out)) out=out.replace(new RegExp('\\b'+escapeRe(k)+'\\b','gi'),dict[k]);
    }
    const wm=wordMaps[lang]||{};
    for(const k of Object.keys(wm).sort((a,b)=>b.length-a.length)){
      if(out.includes(k)&&/\s/.test(out))out=out.replace(new RegExp('\\b'+escapeRe(k)+'\\b','g'),wm[k]);
    }
    return out;
  }
  function restoreNode(el){
    if(el.nodeType===3){
      if(el.parentElement?.closest('[data-dog-no-translate]'))return;
      if(el.dataset.dogOriginal!==undefined)el.nodeValue=el.dataset.dogOriginal;
      return;
    }
    if(el.nodeType!==1)return;
    if(el.closest('[data-dog-no-translate]'))return;
    if(el.matches('option')){
      if(el.dataset.dogOriginalText===undefined)el.dataset.dogOriginalText=el.textContent;
      if(el.dataset.dogOriginalValue===undefined)el.dataset.dogOriginalValue=el.value;
      el.value=el.dataset.dogOriginalValue;
      el.textContent=el.dataset.dogOriginalText;
      return;
    }
    if(['INPUT','TEXTAREA'].includes(el.tagName)){
      if(el.dataset.dogOriginalPlaceholder===undefined)el.dataset.dogOriginalPlaceholder=el.getAttribute('placeholder')||'';
      el.setAttribute('placeholder',el.dataset.dogOriginalPlaceholder);
    }
    if(el.getAttribute('title')!==null){if(el.dataset.dogOriginalTitle===undefined)el.dataset.dogOriginalTitle=el.getAttribute('title');el.setAttribute('title',el.dataset.dogOriginalTitle)}
    if(el.getAttribute('aria-label')!==null){if(el.dataset.dogOriginalAria===undefined)el.dataset.dogOriginalAria=el.getAttribute('aria-label');el.setAttribute('aria-label',el.dataset.dogOriginalAria)}
    [...el.childNodes].forEach(restoreNode);
  }
  function translateNode(el){
    if(el.nodeType===3){
      const p=el.parentElement;if(!p||p.closest('[data-dog-no-translate]'))return;
      if(el.dataset.dogOriginal===undefined)el.dataset.dogOriginal=el.nodeValue;
      el.nodeValue=translateText(el.dataset.dogOriginal,current);return;
    }
    if(el.nodeType!==1||el.closest('[data-dog-no-translate]'))return;
    if(el.matches('option')){
      if(el.dataset.dogOriginalText===undefined)el.dataset.dogOriginalText=el.textContent;
      if(el.dataset.dogOriginalValue===undefined)el.dataset.dogOriginalValue=el.value;
      el.value=el.dataset.dogOriginalValue;
      el.textContent=translateText(el.dataset.dogOriginalText,current);return;
    }
    if(['INPUT','TEXTAREA'].includes(el.tagName)){
      if(el.dataset.dogOriginalPlaceholder===undefined)el.dataset.dogOriginalPlaceholder=el.getAttribute('placeholder')||'';
      const ph=el.dataset.dogOriginalPlaceholder;if(ph)el.setAttribute('placeholder',translateText(ph,current));
    }
    if(el.getAttribute('title')!==null){if(el.dataset.dogOriginalTitle===undefined)el.dataset.dogOriginalTitle=el.getAttribute('title');el.setAttribute('title',translateText(el.dataset.dogOriginalTitle,current))}
    if(el.getAttribute('aria-label')!==null){if(el.dataset.dogOriginalAria===undefined)el.dataset.dogOriginalAria=el.getAttribute('aria-label');el.setAttribute('aria-label',translateText(el.dataset.dogOriginalAria,current))}
    [...el.childNodes].forEach(translateNode);
  }
  let applying=false;
  function apply(){
    if(applying)return;
    applying=true;
    try{
      document.documentElement.lang=current;
      const sel=document.getElementById('language-select');if(sel)sel.value=current;
      restoreNode(document.body);translateNode(document.body);
    }finally{applying=false;}
  }
  function translateAdded(root){
    if(applying||!root)return;
    applying=true;
    try{translateNode(root);}finally{applying=false;}
  }
  window.DogLang={get:()=>current,set(lang){if(!LANGS[lang])return;current=lang;localStorage.setItem('dogrh_lang',lang);apply();}};
  function mount(){
    const actions=document.querySelector('.top-actions');if(!actions)return;
    let sel=document.getElementById('language-select');
    if(!sel){
      const wrap=document.createElement('label');wrap.className='language-picker';wrap.title='Sprache / Language';
      sel=document.createElement('select');sel.id='language-select';sel.setAttribute('aria-label','Sprache');
      Object.entries(LANGS).forEach(([code,x])=>{const o=document.createElement('option');o.value=code;o.textContent=x.flag+' '+x.label;sel.appendChild(o)});
      wrap.appendChild(sel);actions.prepend(wrap);
    }
    sel.onchange=()=>DogLang.set(sel.value);
    sel.value=current;
    apply();
    const obs=new MutationObserver(muts=>{for(const m of muts){for(const n of m.addedNodes||[]){if(n.nodeType===1||n.nodeType===3)translateAdded(n)}}});
    obs.observe(document.body,{childList:true,subtree:true});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
